# Manipulate PyTorch Tensors
<hr>

## Matrix manipulation

In [19]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [9]:
import numpy as np
# write your code here

A = np.array([[1,2], [3, 4]])
B = np.array([[10, 20], [30, 40]])
C = A + B

# print
print(A)
print('')
print(B)
print('')
print(C)

[[1 2]
 [3 4]]

[[10 20]
 [30 40]]

[[11 22]
 [33 44]]


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [17]:
# write your code here

print(A.ndim)    # print the dimension of the matrix A
print('')
print(A.size)    # print the size of the matrix A
print('')
print(type(A))    # print the type of the matrix A

2

4

<class 'numpy.ndarray'>


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [26]:

# write your code here

A_long = torch.tensor(A, dtype = torch.long)

print(type(A_long))    # print the type of A_long
print('')
print(type(A))    # print the type of A

<class 'torch.Tensor'>

<class 'torch.Tensor'>


C:\Users\alber\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [40]:

# write your code here

A = torch.rand(5,2,3)

print(A)
print(type(A))    # print the type of A
print(A.dim())    # print the dimension of A
print(A.size())    # print the size of A
print(A.dim())    # print the size of the middle (second) dimension

tensor([[[6.6428e-01, 3.7005e-01, 4.2914e-01],
         [7.7908e-02, 2.2163e-01, 6.9658e-01]],

        [[7.2343e-01, 5.6411e-01, 4.9782e-01],
         [9.6715e-01, 7.2473e-01, 4.1369e-01]],

        [[1.5576e-01, 7.4846e-01, 4.9126e-01],
         [1.3548e-02, 1.5447e-01, 2.5739e-01]],

        [[2.1826e-01, 7.6579e-01, 8.3029e-04],
         [5.7527e-01, 3.3980e-01, 1.4584e-02]],

        [[6.5166e-01, 9.2951e-01, 6.2565e-01],
         [2.8547e-01, 9.7493e-01, 7.3479e-01]]])
<class 'torch.Tensor'>
3
torch.Size([5, 2, 3])
3


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [ ]:

# write your code here

A = 

print(A)
